FunctionName: Continue
FunctionProperties:
  ModelPath:
  XGoalPosition: 9.0
  YGoalPosition: 10.0
  LearningModel: PPO
  Length: 5000
  SaveDataAfterFinished: False
  SaveDataProperties:
    CsvFilePath: /workspaces/MLSzakdoga/resources/processedData/tensorboard_data.csv