FunctionName: Learn
FunctionProperties:
  XGoalPosition: 9.0
  YGoalPosition: 10.0
  LearningModel: PPO
  Length: 10000
  SaveDataAfterFinished: True
  SaveDataProperties:
    CsvFilePath: /workspaces/MLSzakdoga/resources/processedData/tensorboard_data.csv